# Generated by Django 3.0 on 2020-11-28 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, default='', null=True)),
                ('end_date', models.DateField(blank=True, default='', null=True)),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime(2020, 11, 28, 8, 56, 9, 112887, tzinfo=utc), null=True)),
                ('end_time', models.TimeField(blank=True, default='', null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
